login.html when navigating to subpages, ui fixes for pagination on works/grants, browse by updates, Fixes #169 #220
ucd-library/aggie-experts pull request #261
Opened 2023-11-03 20:27 UTC by UcDust

2023-11-03 20:28 UTC, UcDust commented
@qjhart @Vensberg 

This addresses the following items:

-fix for browse AZ, can still click inactive letters
-search loading, … for number of results instead of showing the number of results from the previous search
-fix login, not requiring login if nav to places other than home, like http://localhost/search/x directly
-grants pagination. If I click on page 2 of grants, then click on "return to profile" then click back on grants, page 2 opens up. This happens even if I navigate to multiple pages in between returning to "see all grants". 
-same for works list

2023-11-06 18:37 UTC, qjhart requested changes
Plz remove the submodule.

2023-11-06 18:37 UTC, qjhart commented on ae_new_project
What's with this new sub-module.  This looks wrong.

2023-11-06 18:40 UTC, UcDust commented on ae_new_project
Good call, that should be removed now.

2023-11-06 18:42 UTC, qjhart approved these changes

2023-11-06 18:43 UTC, merged