Rk cdl timeout
ucd-library/aggie-experts pull request #272
Opened 2023-11-14 00:04 UTC by rakunkel-ucd

timeout and error try/catch/continue
Bunyan logger

2023-11-20 01:42 UTC, rakunkel-ucd commented
@qjhart - added Friday work to this PR

2023-11-28 00:41 UTC, qjhart requested changes

2023-11-28 00:41 UTC, qjhart commented on harvest/experts-client/package.json
> +    "winston": "^3.11.0",
You can remove this right ?

2023-11-28 00:42 UTC, rakunkel-ucd commented
Yes

Roger Kunkel
UC Davis Library
Online Strategy


From: Quinn Hart ***@***.***>
Date: Monday, November 27, 2023 at 4:41 PM
To: ucd-library/aggie-experts ***@***.***>
Cc: Roger Kunkel ***@***.***>, Author ***@***.***>
Subject: Re: [ucd-library/aggie-experts] Rk cdl timeout (PR #272)

@qjhart requested changes on this pull request.

________________________________

In harvest/experts-client/package.json<https://github.com/ucd-library/aggie-experts/pull/272#discussion_r1406942121>:

>      "quadstore": "^11.0.8",

     "quadstore-comunica": "=3.0.0",

     "rdf-data-factory": "^1.1.0",

     "readable-stream": "^4.3.0",

     "string-to-stream": "^3.0.1",

+    "winston": "^3.11.0",

You can remove this right ?

—
Reply to this email directly, view it on GitHub<https://github.com/ucd-library/aggie-experts/pull/272#pullrequestreview-1751684327>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A52JJTDFPLR3BJQOFSPPXWTYGUXLBAVCNFSM6AAAAAA7J6LIWWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONJRGY4DIMZSG4>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-11-28 01:02 UTC, rakunkel-ucd commented on harvest/experts-client/package.json
> +    "winston": "^3.11.0",
Yes, removed.

2023-11-28 23:43 UTC, qjhart approved these changes

2023-11-28 23:56 UTC, merged