Add lastmodified to base model Index
ucd-library/aggie-experts pull request #648
Opened 2024-11-01 23:34 UTC by rakunkel-ucd

Use an ingest pipeline to populate a lastmodified date field when creating am ES search from within models.

2024-11-01 23:40 UTC, rakunkel-ucd commented
The ingest pipeline is PUT to ES as a one-time operation. Then the index settings can reference it.

2024-11-01 23:51 UTC, rakunkel-ucd commented
https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html

2024-11-13 23:20 UTC, rakunkel-ucd commented on services/base-service/models/base/model.js
> +    // Check if our ingest pipeline exists, install if not
Trying to call ingest_pipeline - doesn't seem to create the pipeline.

2024-11-13 23:21 UTC, rakunkel-ucd commented on services/base-service/models/base/model.js
> +  async verify_ingest_pipeline(pipelineId, pipelineBody) {
function to verify the pipeline

2024-11-13 23:22 UTC, rakunkel-ucd commented on services/base-service/models/base/model.js
> +    // Check if our ingest pipeline exists, install if not
When does model.render get called?

2024-11-13 23:25 UTC, rakunkel-ucd commented
Can't seem to successfully create the ingest_pipeline. 
From dbsync log:
2024-11-13 11:04:49 {"name":"fin-server-generic-localhost","hostname":"85abe3427ff0","pid":19,"level":50,"msg":"Failed to update: /expert/qX78TtWs/ark:/87287/d7mh2m/6963582 ResponseError: illegal_argument_exception: [illegal_argument_exception] Reason: pipeline with id [aggie-experts-pipeline] does not exist

etc.

2024-12-04 01:07 UTC, rakunkel-ucd commented
Debugging search template for sitefarm api GET.

2024-12-05 00:29 UTC, rakunkel-ucd commented
Last commit ([e65a1f2](https://github.com/ucd-library/aggie-experts/pull/648/commits/e65a1f2ce6da7372fdbaeddc29c5619beb0fc373) has working version using the subselect method.

http://localhost/api/sitefarm/experts/iamId:1000019077,ucdPersonUUID:00021386,expertId:qX78TtWs?modified_since=2024-12-01

2024-12-05 23:34 UTC, qjhart requested changes
@rakunkel-ucd I tried to limit the changes  so that 
- it would run the verify_template() command to add it into elasticsearch

Then I really just verified using the kibana console. The easiest way to do that is :

Mount the moels in your dev

```bash
bin/aggie-experts --env=dev --mount=models,api build setup
```

THen, if you want to update the search template do this:

1) DELETE the script
2)  Restart uber/gateway.  This makes your new script in the images
```bash
dc restart uber dbsync gateway; dc logs -f uber
```
3) Run a query
```bash
http http://localhost/api/sitefarm/experts/email:qjhart@ucdavis.edu Authorization:"Bearer $jwt" Content-type:application/json
```
That will reload the script, so you can use the Kibana console.


This is how I test in the kibana console.

``` http
GET _scripts/modified-date
DELETE _scripts/modified-date
GET _render/template
{
  "id":"modified-date",
    "params":{
    "qx":"climate",
    "expert":["expert/LDdgBTXN","expert/DffIr7cE"]
  }
}

GET expert-read/_search/template
{
  "id":"modified-date",
    "params":{
    "qx":"climate",
    "expert":["expert/LDdgBTXN","expert/DffIr7cE"]
  }
}
```

2024-12-05 23:34 UTC, qjhart commented on services/base-service/models/sitefarm/template/modified-date.js
> +                  "terms": {
This is where we find experts with matching ids.  However, the way it's written now, it will fail if you don't include any epxerts.

2024-12-05 23:34 UTC, qjhart commented on services/base-service/models/middleware.js
> +    req.query.expert=experts.join(',');
This converts the sitefarm potential ids to a comma separated string of experts.  It's returned that way to match our other tools that allow `expert=expert/FOOB,expert/BARfar` as a query parameter

2024-12-05 23:34 UTC, qjhart commented on services/base-service/models/sitefarm/api.js
> +  // has_access('sitefarm'),
I removed this because it was hanging, and I didn't want to verify

2024-12-05 23:34 UTC, qjhart commented on services/base-service/models/base/model.js
> +    // Throw error to see stack trace
Remove this?

2024-12-05 23:34 UTC, qjhart commented on services/base-service/models/base/schema/minimal.json
> +    "lastmodified": {
Is this used?

2024-12-05 23:34 UTC, qjhart commented on services/base-service/models/sitefarm/api.js
> +  // has_access('sitefarm'),
Also, I'm curious as why this is a path parameter and not a query parameter

2024-12-05 23:53 UTC, rakunkel-ucd commented on services/base-service/models/base/schema/minimal.json
> +    "lastmodified": {
No. Should be removed.

2024-12-19 00:15 UTC, qjhart approved these changes

2024-12-23 20:05 UTC, merged